name: iOS

on: [push]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v1
    #   with:
    #     fetch-depth: 1

    # - name: Node
    #   uses: actions/setup-node@v1

    # - name: Cache node modules
    #   uses: actions/cache@v1
    #   id: cache
    #   with:
    #     path: node_modules
    #     key: node-modules-${{ hashFiles('**/yarn.lock') }}

    # - name: Rebuild detox
    #   if: steps.cache.outputs.cache-hit == 'true'
    #   run: yarn detox clean-framework-cache && yarn detox build-framework-cache

    - name: Install Dependencies
      run: |
        git clone https://github.com/InstaSell/Instasell-new.git
        cd Instasell-new
        git checkout rahul/detox-setup
        yarn

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && rm -rf Podfile.lock && pod install && cd ..
    - run: arch -x86_64 brew tap wix/brew
    - run: arch -x86_64 brew install applesimutils
    - run: yarn detox build -c ios 
    - run: yarn detox test -c ios